### ISSUE TITLE
Adding Concordia ID verification

### ISSUE THREAD

**Issue by Transurgeon** [Transurgeon/shopping-cart#4]
We need to add an additional layer of verification.
This can be done in the following steps:
1. Modify the UserBean to add a new attribute called ConcordiaID
2. Are we doing two-factor authentication?

**Comment by Transurgeon** [comment]
we will need more helper functions.
1. Concordia ID needs to be 8 digit number starting with "4".
2. email needs to end with "@concordia.ca"
3. username needs to be unique

**Comment by chloedaull** [comment]
this issue is completed by #25
